android:
- src/Core/*
- src/Android/*

iOS:
- src/Core/*
- lib/ios/*
- src/iOS/*
- src/iOS.Autofill/*
- src/iOS.Core/*
- src/iOS.Extension/*
- src/iOS.ShareExtension/*
- src/iOS.Widget/*
- src/watchOS/*

watchOS:
- src/watchOS/*