name: Release

on:
  workflow_dispatch:

jobs:
  android:
    name: Android Build
    runs-on: windows-latest
    steps:
      - name: Download Play Store .aab artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: com.x8bit.bitwarden.aab

      - name: Download Play Store .apk artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: com.x8bit.bitwarden.apk

      - name: Download F-Droid .apk artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: com.x8bit.bitwarden-fdroid.apk

      - name: Deploy to Play Store
        if: false
        run: |
          PUBLISHER_PATH="./store/google/Publisher/bin/Release/netcoreapp2.0/Publisher.dll"
          CREDS_PATH="$HOME/secrets/play_creds.json"
          AAB_PATH="./com.x8bit.bitwarden.aab"
          TRACK="internal"

          dotnet $PUBLISHER_PATH $CREDS_PATH $AAB_PATH $TRACK
        shell: bash

      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: TEST - Get Mobile Version
        run: |
          ver=$(sed-n -e '/android:versionName/ s/.*\= *//p' ./src/Android/Properties/AndroidManifest.xml)
          echo "VERSION: $ver"
        shell: bash

      - name: Upload release assets
        if: false
        run: |
          hub release edit \
            -a ./com.x8bit.bitwarden.aab \
            -a ./com.x8bit.bitwarden.apk \
            -a ./com.x8bit.bitwarden-fdroid.apk \
            -m "Version ${RELEASE_TAG_NAME//v}" \
            $RELEASE_TAG_NAME
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}


  android-ubuntu:
    name: Android Ubuntu Build
    runs-on: ubuntu-latest
    needs: android
    steps:
      - name: Download F-Droid .apk artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: com.x8bit.bitwarden-fdroid.apk

      - name: Set up Node
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: '10.x'

      - name: Set up F-Droid server
        run: |
          sudo apt-get -qq update
          sudo apt-get -qqy install --no-install-recommends fdroidserver wget

      - name: Set up Git credentials
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://${ACCESS_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials
          git config --global user.email "ci@bitwarden.com"
          git config --global user.name "Bitwarden CI"

      - name: Print environment
        run: |
          node --version
          npm --version
          git --version
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install Node dependencies
        run: npm install

      - name: Decrypt secrets
        run: |
          mkdir -p ~/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" --output ./store/fdroid/keystore.jks ./.github/secrets/store_fdroid-keystore.jks.gpg
        env:
          DECRYPT_FILE_PASSWORD: ${{ secrets.DECRYPT_FILE_PASSWORD }}

      - name: Compile for F-Droid Store
        if: false
        run: |
          cd $GITHUB_WORKSPACE
          mkdir dist
          cp CNAME ./dist
          cd store
          chmod 600 fdroid/config.py fdroid/keystore.jks
          mkdir -p temp/fdroid
          TEMP_DIR="$GITHUB_WORKSPACE/store/temp/fdroid"
          cd fdroid
          echo "keypass=\"$FDROID_STORE_KEYSTORE_PASSWORD\"" >>config.py
          echo "keystorepass=\"$FDROID_STORE_KEYSTORE_PASSWORD\"" >>config.py
          echo "local_copy_dir=\"$TEMP_DIR\"" >>config.py
          mkdir -p repo
          curl -Lo repo/com.x8bit.bitwarden-fdroid.apk \
          https://github.com/bitwarden/mobile/releases/download/$RELEASE_TAG_NAME/com.x8bit.bitwarden-fdroid.apk
          fdroid update
          fdroid server update
          cd ..
          rm -rf temp/fdroid/archive
          mv -v temp/fdroid ../dist
          cd fdroid
          cp index.html btn.png qr.png ../../dist/fdroid
          cd $GITHUB_WORKSPACE
        env:
          FDROID_STORE_KEYSTORE_PASSWORD: ${{ secrets.FDROID_STORE_KEYSTORE_PASSWORD }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Deploy to gh-pages
        if: false
        run: npm run deploy


  ios:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Download App Store .ipa artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: Bitwarden.ipa

      - name: Deploy to App Store
        if: false
        run: |
          xcrun altool --upload-app --type ios --file "./bitwarden-export/Bitwarden.ipa" \
              --username "$APPLE_ID_USERNAME" --password "$APPLE_ID_PASSWORD"
        shell: bash
        env:
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload release assets
        if: false
        run: |
          hub release edit \
            -a ./bitwarden-export/Bitwarden.ipa \
            -m "Version ${RELEASE_TAG_NAME//v}" \
            $RELEASE_TAG_NAME
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
