---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**
  workflow_dispatch:

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@main
